/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param `data` 
 */


data class AuthRegisterPost201Response (

    @Json(name = "status")
    val status: AuthRegisterPost201Response.Status? = null,

    @Json(name = "data")
    val `data`: UserFull? = null

) {

    /**
     * 
     *
     * Values: success
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "success") success("success");
    }
}

