/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param expiresIn 
 * @param user 
 */


data class AuthResponse (

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "expiresIn")
    val expiresIn: kotlin.Int? = null,

    @Json(name = "user")
    val user: UserSummary? = null

)

