/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param barcode 
 * @param name 
 * @param brand 
 * @param category 
 */


data class CreateProductRequest (

    @Json(name = "barcode")
    val barcode: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null

)

