/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param quantity 
 * @param expiryDate 
 */


data class FridgeItemUpdateRequest (

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,

    @Json(name = "expiryDate")
    val expiryDate: java.time.LocalDate? = null

)

