/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param role 
 * @param itemCount 
 * @param memberCount 
 * @param urgentCount Nombre de produits expirant dans les 3 prochains jours
 * @param updatedAt 
 * @param ownerId 
 * @param createdAt 
 */


data class FridgeFull (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "role")
    val role: FridgeFull.Role? = null,

    @Json(name = "itemCount")
    val itemCount: kotlin.Int? = null,

    @Json(name = "memberCount")
    val memberCount: kotlin.Int? = null,

    /* Nombre de produits expirant dans les 3 prochains jours */
    @Json(name = "urgentCount")
    val urgentCount: kotlin.Int? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "ownerId")
    val ownerId: java.util.UUID? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: owner,collaborator
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "collaborator") collaborator("collaborator");
    }
}

