/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId 
 * @param quantity 
 * @param expiryDate 
 */


data class FridgeItemRequest (

    @Json(name = "productId")
    val productId: java.util.UUID,

    @Json(name = "quantity")
    val quantity: kotlin.Int,

    @Json(name = "expiryDate")
    val expiryDate: java.time.LocalDate

)

