/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param product 
 * @param quantity 
 * @param expiryDate 
 * @param urgent true si le produit expire dans 3 jours ou moins
 * @param daysUntilExpiry Négatif si déjà expiré
 * @param addedBy 
 * @param createdAt 
 * @param updatedAt 
 */


data class FridgeItem (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "product")
    val product: FridgeItemProduct? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,

    @Json(name = "expiryDate")
    val expiryDate: java.time.LocalDate? = null,

    /* true si le produit expire dans 3 jours ou moins */
    @Json(name = "urgent")
    val urgent: kotlin.Boolean? = null,

    /* Négatif si déjà expiré */
    @Json(name = "daysUntilExpiry")
    val daysUntilExpiry: kotlin.Int? = null,

    @Json(name = "addedBy")
    val addedBy: UserSummary? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

)

