/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.monnier.frigapp.generate.infrastructure.BrandString
import com.monnier.frigapp.generate.infrastructure.NullableUri
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param brand 
 * @param imageUrl 
 */


data class FridgeItemProduct (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @BrandString
    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @NullableUri
    @Json(name = "imageUrl")
    val imageUrl: java.net.URI? = null

)

