/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param firstName 
 * @param email 
 * @param role 
 * @param joinedAt 
 */


data class MemberSummary (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "userId")
    val userId: java.util.UUID? = null,

    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "role")
    val role: MemberSummary.Role? = null,

    @Json(name = "joinedAt")
    val joinedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: owner,collaborator
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "collaborator") collaborator("collaborator");
    }
}

