/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.monnier.frigapp.generate.infrastructure.BrandString
import com.monnier.frigapp.generate.infrastructure.IntOrObject
import com.monnier.frigapp.generate.infrastructure.NullableUri
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param barcode 
 * @param name 
 * @param brand 
 * @param category 
 * @param imageUrl 
 * @param source 
 * @param suggestedExpiryDays Durée de conservation suggérée en jours selon la catégorie
 */


data class Product (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "barcode")
    val barcode: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @BrandString
    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @NullableUri
    @Json(name = "imageUrl")
    val imageUrl: java.net.URI? = null,

    @Json(name = "source")
    val source: Product.Source? = null,

    /* Durée de conservation suggérée en jours selon la catégorie */
    @IntOrObject
    @Json(name = "suggestedExpiryDays")
    val suggestedExpiryDays: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: open_food_facts,manual
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "open_food_facts") open_food_facts("open_food_facts"),
        @Json(name = "manual") manual("manual");
    }
}

