/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.monnier.frigapp.generate.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param firstName 
 * @param email 
 */


data class UserSummary (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null

)

