/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.frigapp.frigappapi.controller.api;

import com.frigapp.frigappapi.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-26T22:36:13.511413300+01:00[Europe/Paris]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "Items", description = "Gestion des items dans un frigo")
public interface ItemsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /fridges/{fridgeId}/items : Lister les items du frigo
     * Retourne les items triés par date de péremption. Inclut un flag urgent pour les produits expirant dans 3 jours ou moins.
     *
     * @param fridgeId  (required)
     * @param sort Ordre de tri (optional, default to expiry_asc)
     * @return Liste des items (status code 200)
     *         or Token JWT absent ou invalide (status code 401)
     *         or Action non autorisée pour ce rôle (status code 403)
     *         or Ressource introuvable (status code 404)
     */
    @Operation(
        operationId = "fridgesFridgeIdItemsGet",
        summary = "Lister les items du frigo",
        description = "Retourne les items triés par date de péremption. Inclut un flag urgent pour les produits expirant dans 3 jours ou moins.",
        tags = { "Items" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Liste des items", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FridgesFridgeIdItemsGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Token JWT absent ou invalide", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Action non autorisée pour ce rôle", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ressource introuvable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/fridges/{fridgeId}/items",
        produces = { "application/json" }
    )
    
    default ResponseEntity<FridgesFridgeIdItemsGet200Response> fridgesFridgeIdItemsGet(
        @Parameter(name = "fridgeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("fridgeId") UUID fridgeId,
        @Parameter(name = "sort", description = "Ordre de tri", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "expiry_asc") String sort
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : [ { \"expiryDate\" : \"2026-03-25\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"product\" : { \"imageUrl\" : \"https://openapi-generator.tech\", \"name\" : \"Lait entier\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"brand\" : \"Lactel\" }, \"quantity\" : 1, \"addedBy\" : { \"firstName\" : \"Nathanaël\", \"id\" : \"550e8400-e29b-41d4-a716-446655440000\", \"email\" : \"nathanael@email.com\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"urgent\" : true, \"daysUntilExpiry\" : 2, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"expiryDate\" : \"2026-03-25\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"product\" : { \"imageUrl\" : \"https://openapi-generator.tech\", \"name\" : \"Lait entier\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"brand\" : \"Lactel\" }, \"quantity\" : 1, \"addedBy\" : { \"firstName\" : \"Nathanaël\", \"id\" : \"550e8400-e29b-41d4-a716-446655440000\", \"email\" : \"nathanael@email.com\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"urgent\" : true, \"daysUntilExpiry\" : 2, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ], \"status\" : \"success\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /fridges/{fridgeId}/items/{itemId} : Supprimer un item
     * Retire un item du frigo. Déclenche une notification WebSocket ITEM_DELETED.
     *
     * @param fridgeId  (required)
     * @param itemId  (required)
     * @return Item supprimé (status code 204)
     *         or Token JWT absent ou invalide (status code 401)
     *         or Action non autorisée pour ce rôle (status code 403)
     *         or Ressource introuvable (status code 404)
     */
    @Operation(
        operationId = "fridgesFridgeIdItemsItemIdDelete",
        summary = "Supprimer un item",
        description = "Retire un item du frigo. Déclenche une notification WebSocket ITEM_DELETED.",
        tags = { "Items" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Item supprimé"),
            @ApiResponse(responseCode = "401", description = "Token JWT absent ou invalide", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Action non autorisée pour ce rôle", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ressource introuvable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/fridges/{fridgeId}/items/{itemId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> fridgesFridgeIdItemsItemIdDelete(
        @Parameter(name = "fridgeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("fridgeId") UUID fridgeId,
        @Parameter(name = "itemId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("itemId") UUID itemId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /fridges/{fridgeId}/items/{itemId} : Modifier un item
     * Modifie la DLC et/ou la quantité. Déclenche une notification WebSocket ITEM_UPDATED.
     *
     * @param fridgeId  (required)
     * @param itemId  (required)
     * @param fridgeItemUpdateRequest  (required)
     * @return Item modifié (status code 200)
     *         or Données invalides (status code 400)
     *         or Token JWT absent ou invalide (status code 401)
     *         or Action non autorisée pour ce rôle (status code 403)
     *         or Ressource introuvable (status code 404)
     */
    @Operation(
        operationId = "fridgesFridgeIdItemsItemIdPut",
        summary = "Modifier un item",
        description = "Modifie la DLC et/ou la quantité. Déclenche une notification WebSocket ITEM_UPDATED.",
        tags = { "Items" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Item modifié", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FridgesFridgeIdItemsPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Données invalides", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Token JWT absent ou invalide", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Action non autorisée pour ce rôle", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ressource introuvable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/fridges/{fridgeId}/items/{itemId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FridgesFridgeIdItemsPost201Response> fridgesFridgeIdItemsItemIdPut(
        @Parameter(name = "fridgeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("fridgeId") UUID fridgeId,
        @Parameter(name = "itemId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("itemId") UUID itemId,
        @Parameter(name = "FridgeItemUpdateRequest", description = "", required = true) @Valid @RequestBody FridgeItemUpdateRequest fridgeItemUpdateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"expiryDate\" : \"2026-03-25\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"product\" : { \"imageUrl\" : \"https://openapi-generator.tech\", \"name\" : \"Lait entier\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"brand\" : \"Lactel\" }, \"quantity\" : 1, \"addedBy\" : { \"firstName\" : \"Nathanaël\", \"id\" : \"550e8400-e29b-41d4-a716-446655440000\", \"email\" : \"nathanael@email.com\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"urgent\" : true, \"daysUntilExpiry\" : 2, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, \"status\" : \"success\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /fridges/{fridgeId}/items : Ajouter un item au frigo
     * Ajoute un produit au frigo. Déclenche une notification WebSocket ITEM_ADDED à tous les membres.
     *
     * @param fridgeId  (required)
     * @param fridgeItemRequest  (required)
     * @return Item ajouté (status code 201)
     *         or Données invalides (status code 400)
     *         or Token JWT absent ou invalide (status code 401)
     *         or Action non autorisée pour ce rôle (status code 403)
     *         or Ressource introuvable (status code 404)
     */
    @Operation(
        operationId = "fridgesFridgeIdItemsPost",
        summary = "Ajouter un item au frigo",
        description = "Ajoute un produit au frigo. Déclenche une notification WebSocket ITEM_ADDED à tous les membres.",
        tags = { "Items" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Item ajouté", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FridgesFridgeIdItemsPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Données invalides", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Token JWT absent ou invalide", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Action non autorisée pour ce rôle", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ressource introuvable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/fridges/{fridgeId}/items",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FridgesFridgeIdItemsPost201Response> fridgesFridgeIdItemsPost(
        @Parameter(name = "fridgeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("fridgeId") UUID fridgeId,
        @Parameter(name = "FridgeItemRequest", description = "", required = true) @Valid @RequestBody FridgeItemRequest fridgeItemRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"expiryDate\" : \"2026-03-25\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"product\" : { \"imageUrl\" : \"https://openapi-generator.tech\", \"name\" : \"Lait entier\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"brand\" : \"Lactel\" }, \"quantity\" : 1, \"addedBy\" : { \"firstName\" : \"Nathanaël\", \"id\" : \"550e8400-e29b-41d4-a716-446655440000\", \"email\" : \"nathanael@email.com\" }, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"urgent\" : true, \"daysUntilExpiry\" : 2, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, \"status\" : \"success\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"FRIDGE_NOT_FOUND\", \"message\" : \"Le frigo demandé n'existe pas.\" }, \"status\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
